### ISSUE TITLE
Confused on usage

### ISSUE THREAD

**Issue by surayashivji** [ykyouhei/SwiftyConfiguration#1]
Hi! Thanks for the great project. 

In terms of usage, where would you define the plist keys? You have a Keys extension but what is the Keys class? A bit insure on where to configure this. Thanks!

**Comment by ykyouhei** [comment]
Hi!
Key and Keys has been defined in this library.
https://github.com/ykyouhei/SwiftyConfiguration/blob/master/SwiftyConfiguration/Classes/Configuration.swift#L28

**Comment by surayashivji** [comment]
Thank you for the quick response! My bad for not seeing that-- I forgot to import it and got a bit lost. The project works great! 😃

**Comment by surayashivji** [comment]
Also-- README update for Swift 3: 
        let plist = Bundle.main.path(forResource: "Configuration", ofType: "plist")!
        let config = Configuration(plistPath: plist)

**Comment by ykyouhei** [comment]
OK! Later update the README.
